-- ============================================================
-- V1 - Initial Reservation System Database Schema
-- ============================================================

-- ============================================================
-- Users
-- ============================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,

    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);


-- ============================================================
-- Rooms
-- ============================================================

CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(255) NOT NULL,
    room_type VARCHAR(255) NOT NULL,
    available BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_rooms_room_number UNIQUE (room_number)
);


-- ============================================================
-- Reservations
-- ============================================================

CREATE TABLE reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    room_id BIGINT,
    user_id BIGINT,

    customer_name VARCHAR(255),
    room_type VARCHAR(255),

    status VARCHAR(255),

    check_in_date DATE,
    check_out_date DATE,

    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_reservation_room
        FOREIGN KEY (room_id)
        REFERENCES rooms (id),

    CONSTRAINT fk_reservation_user
        FOREIGN KEY (user_id)
        REFERENCES users (id),

    CONSTRAINT chk_reservation_status
        CHECK (
            status IS NULL
            OR status IN (
                'PENDING',
                'CONFIRMED',
                'CANCELLED'
            )
        )
);


-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX idx_reservation_room_id
    ON reservation (room_id);

CREATE INDEX idx_reservation_user_id
    ON reservation (user_id);

CREATE INDEX idx_reservation_customer_name
    ON reservation (customer_name);

CREATE INDEX idx_reservation_room_type
    ON reservation (room_type);

CREATE INDEX idx_reservation_check_in_date
    ON reservation (check_in_date);

CREATE INDEX idx_reservation_check_out_date
    ON reservation (check_out_date);